##
## EPITECH PROJECT, 2023
## libraries
## File description:
## Makefile
##

all:
	make -C malloc
	make -C open
	make -C read
	make -C stat

fclean:
	make -C malloc fclean
	make -C open fclean
	make -C read fclean
	make -C stat fclean
